// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qr.proto

package gqr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Data_Recovery int32

const (
	// Level L: 7% error recovery.
	Data_LOW Data_Recovery = 0
	// Level M: 15% error recovery. Good default choice.
	Data_MEDIUM Data_Recovery = 1
	// Level Q: 25% error recovery.
	Data_HIGH Data_Recovery = 2
	// Level H: 30% error recovery.
	Data_HIGHEST Data_Recovery = 3
)

var Data_Recovery_name = map[int32]string{
	0: "LOW",
	1: "MEDIUM",
	2: "HIGH",
	3: "HIGHEST",
}
var Data_Recovery_value = map[string]int32{
	"LOW":     0,
	"MEDIUM":  1,
	"HIGH":    2,
	"HIGHEST": 3,
}

func (x Data_Recovery) String() string {
	return proto.EnumName(Data_Recovery_name, int32(x))
}
func (Data_Recovery) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_qr_62d9492e5de4f718, []int{0, 0}
}

type Data struct {
	RecoveryLevel        Data_Recovery `protobuf:"varint,1,opt,name=RecoveryLevel,enum=gqr.Data_Recovery" json:"RecoveryLevel,omitempty"`
	Size                 int32         `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Data                 string        `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_qr_62d9492e5de4f718, []int{0}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetRecoveryLevel() Data_Recovery {
	if m != nil {
		return m.RecoveryLevel
	}
	return Data_LOW
}

func (m *Data) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Data) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Image struct {
	ContentType          string   `protobuf:"bytes,1,opt,name=contentType" json:"contentType,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_qr_62d9492e5de4f718, []int{1}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Image) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "gqr.Data")
	proto.RegisterType((*Image)(nil), "gqr.Image")
	proto.RegisterEnum("gqr.Data_Recovery", Data_Recovery_name, Data_Recovery_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for QR service

type QRClient interface {
	Generate(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Image, error)
}

type qRClient struct {
	cc *grpc.ClientConn
}

func NewQRClient(cc *grpc.ClientConn) QRClient {
	return &qRClient{cc}
}

func (c *qRClient) Generate(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/gqr.QR/Generate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for QR service

type QRServer interface {
	Generate(context.Context, *Data) (*Image, error)
}

func RegisterQRServer(s *grpc.Server, srv QRServer) {
	s.RegisterService(&_QR_serviceDesc, srv)
}

func _QR_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gqr.QR/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRServer).Generate(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

var _QR_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gqr.QR",
	HandlerType: (*QRServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _QR_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qr.proto",
}

func init() { proto.RegisterFile("qr.proto", fileDescriptor_qr_62d9492e5de4f718) }

var fileDescriptor_qr_62d9492e5de4f718 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x9b, 0xdd, 0x6d, 0xbb, 0x3b, 0x55, 0x09, 0x73, 0x5a, 0x3c, 0x85, 0x78, 0x59, 0x2f,
	0x39, 0x54, 0x10, 0x2f, 0xde, 0x5a, 0xda, 0x85, 0x16, 0x31, 0x56, 0x3c, 0xc7, 0x3a, 0x2c, 0x82,
	0x6e, 0xba, 0x31, 0x14, 0xea, 0xaf, 0xf1, 0xa7, 0x4a, 0x22, 0x5d, 0xec, 0xed, 0xe3, 0xe5, 0x65,
	0xde, 0x9b, 0x81, 0xbc, 0x73, 0x6a, 0xe7, 0xac, 0xb7, 0x98, 0x36, 0x9d, 0x93, 0x3f, 0x0c, 0xb2,
	0x99, 0xf1, 0x06, 0xef, 0xe0, 0x5c, 0xd3, 0xd6, 0xee, 0xc9, 0x1d, 0x56, 0xb4, 0xa7, 0x8f, 0x92,
	0x09, 0x56, 0x5d, 0x4c, 0x51, 0x35, 0x9d, 0x53, 0xc1, 0xa1, 0x8e, 0xcf, 0xfa, 0xd4, 0x88, 0x08,
	0xd9, 0xd7, 0xfb, 0x37, 0x95, 0x89, 0x60, 0xd5, 0x50, 0x47, 0x0e, 0xda, 0x9b, 0xf1, 0xa6, 0x4c,
	0x05, 0xab, 0x0a, 0x1d, 0x59, 0xde, 0x42, 0x7e, 0xfc, 0x88, 0x63, 0x48, 0x57, 0x0f, 0x2f, 0x7c,
	0x80, 0x00, 0xa3, 0xf5, 0x7c, 0x56, 0x3f, 0xaf, 0x39, 0xc3, 0x1c, 0xb2, 0x65, 0xbd, 0x58, 0xf2,
	0x04, 0x27, 0x30, 0x0e, 0x34, 0x7f, 0xda, 0xf0, 0x54, 0xde, 0xc3, 0xb0, 0xfe, 0x34, 0x0d, 0xa1,
	0x80, 0xc9, 0xd6, 0xb6, 0x9e, 0x5a, 0xbf, 0x39, 0xec, 0x28, 0x16, 0x2c, 0xf4, 0x7f, 0xa9, 0x8f,
	0x0d, 0x55, 0xce, 0xfe, 0x62, 0xa7, 0xd7, 0x90, 0x3c, 0x6a, 0xbc, 0x82, 0x7c, 0x41, 0x2d, 0x39,
	0xe3, 0x09, 0x8b, 0x7e, 0xa7, 0x4b, 0x88, 0x18, 0xc7, 0xcb, 0xc1, 0xeb, 0x28, 0x1e, 0xe6, 0xe6,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x20, 0xfc, 0xe4, 0x73, 0x24, 0x01, 0x00, 0x00,
}
