// Code generated by protoc-gen-go. DO NOT EDIT.
// source: otp.proto

package twoferrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OTPAlg int32

const (
	OTPAlg_SHA_1   OTPAlg = 0
	OTPAlg_SHA_256 OTPAlg = 1
	OTPAlg_SHA_512 OTPAlg = 2
)

var OTPAlg_name = map[int32]string{
	0: "SHA_1",
	1: "SHA_256",
	2: "SHA_512",
}
var OTPAlg_value = map[string]int32{
	"SHA_1":   0,
	"SHA_256": 1,
	"SHA_512": 2,
}

func (x OTPAlg) String() string {
	return proto.EnumName(OTPAlg_name, int32(x))
}
func (OTPAlg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_otp_21fb56b2fc8393a0, []int{0}
}

type OTPMode int32

const (
	OTPMode_TIME    OTPMode = 0
	OTPMode_COUNTER OTPMode = 1
)

var OTPMode_name = map[int32]string{
	0: "TIME",
	1: "COUNTER",
}
var OTPMode_value = map[string]int32{
	"TIME":    0,
	"COUNTER": 1,
}

func (x OTPMode) String() string {
	return proto.EnumName(OTPMode_name, int32(x))
}
func (OTPMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_otp_21fb56b2fc8393a0, []int{1}
}

type OTPDigits int32

const (
	OTPDigits_SIX   OTPDigits = 0
	OTPDigits_EIGHT OTPDigits = 1
)

var OTPDigits_name = map[int32]string{
	0: "SIX",
	1: "EIGHT",
}
var OTPDigits_value = map[string]int32{
	"SIX":   0,
	"EIGHT": 1,
}

func (x OTPDigits) String() string {
	return proto.EnumName(OTPDigits_name, int32(x))
}
func (OTPDigits) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_otp_21fb56b2fc8393a0, []int{2}
}

type OTPEnrollment struct {
	Issuer               string    `protobuf:"bytes,1,opt,name=issuer" json:"issuer,omitempty"`
	Account              string    `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Alg                  OTPAlg    `protobuf:"varint,3,opt,name=alg,enum=twoferrpc.OTPAlg" json:"alg,omitempty"`
	Mode                 OTPMode   `protobuf:"varint,4,opt,name=mode,enum=twoferrpc.OTPMode" json:"mode,omitempty"`
	Digits               OTPDigits `protobuf:"varint,6,opt,name=digits,enum=twoferrpc.OTPDigits" json:"digits,omitempty"`
	Period               uint32    `protobuf:"varint,7,opt,name=period" json:"period,omitempty"`
	SecretSize           uint32    `protobuf:"varint,8,opt,name=secretSize" json:"secretSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OTPEnrollment) Reset()         { *m = OTPEnrollment{} }
func (m *OTPEnrollment) String() string { return proto.CompactTextString(m) }
func (*OTPEnrollment) ProtoMessage()    {}
func (*OTPEnrollment) Descriptor() ([]byte, []int) {
	return fileDescriptor_otp_21fb56b2fc8393a0, []int{0}
}
func (m *OTPEnrollment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OTPEnrollment.Unmarshal(m, b)
}
func (m *OTPEnrollment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OTPEnrollment.Marshal(b, m, deterministic)
}
func (dst *OTPEnrollment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OTPEnrollment.Merge(dst, src)
}
func (m *OTPEnrollment) XXX_Size() int {
	return xxx_messageInfo_OTPEnrollment.Size(m)
}
func (m *OTPEnrollment) XXX_DiscardUnknown() {
	xxx_messageInfo_OTPEnrollment.DiscardUnknown(m)
}

var xxx_messageInfo_OTPEnrollment proto.InternalMessageInfo

func (m *OTPEnrollment) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *OTPEnrollment) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *OTPEnrollment) GetAlg() OTPAlg {
	if m != nil {
		return m.Alg
	}
	return OTPAlg_SHA_1
}

func (m *OTPEnrollment) GetMode() OTPMode {
	if m != nil {
		return m.Mode
	}
	return OTPMode_TIME
}

func (m *OTPEnrollment) GetDigits() OTPDigits {
	if m != nil {
		return m.Digits
	}
	return OTPDigits_SIX
}

func (m *OTPEnrollment) GetPeriod() uint32 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *OTPEnrollment) GetSecretSize() uint32 {
	if m != nil {
		return m.SecretSize
	}
	return 0
}

type OTPEnrollmentResponse struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OTPEnrollmentResponse) Reset()         { *m = OTPEnrollmentResponse{} }
func (m *OTPEnrollmentResponse) String() string { return proto.CompactTextString(m) }
func (*OTPEnrollmentResponse) ProtoMessage()    {}
func (*OTPEnrollmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_otp_21fb56b2fc8393a0, []int{1}
}
func (m *OTPEnrollmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OTPEnrollmentResponse.Unmarshal(m, b)
}
func (m *OTPEnrollmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OTPEnrollmentResponse.Marshal(b, m, deterministic)
}
func (dst *OTPEnrollmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OTPEnrollmentResponse.Merge(dst, src)
}
func (m *OTPEnrollmentResponse) XXX_Size() int {
	return xxx_messageInfo_OTPEnrollmentResponse.Size(m)
}
func (m *OTPEnrollmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OTPEnrollmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OTPEnrollmentResponse proto.InternalMessageInfo

func (m *OTPEnrollmentResponse) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *OTPEnrollmentResponse) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type OTPValidate struct {
	Otp                  string   `protobuf:"bytes,1,opt,name=otp" json:"otp,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OTPValidate) Reset()         { *m = OTPValidate{} }
func (m *OTPValidate) String() string { return proto.CompactTextString(m) }
func (*OTPValidate) ProtoMessage()    {}
func (*OTPValidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_otp_21fb56b2fc8393a0, []int{2}
}
func (m *OTPValidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OTPValidate.Unmarshal(m, b)
}
func (m *OTPValidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OTPValidate.Marshal(b, m, deterministic)
}
func (dst *OTPValidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OTPValidate.Merge(dst, src)
}
func (m *OTPValidate) XXX_Size() int {
	return xxx_messageInfo_OTPValidate.Size(m)
}
func (m *OTPValidate) XXX_DiscardUnknown() {
	xxx_messageInfo_OTPValidate.DiscardUnknown(m)
}

var xxx_messageInfo_OTPValidate proto.InternalMessageInfo

func (m *OTPValidate) GetOtp() string {
	if m != nil {
		return m.Otp
	}
	return ""
}

func (m *OTPValidate) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type OTPValidateResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OTPValidateResponse) Reset()         { *m = OTPValidateResponse{} }
func (m *OTPValidateResponse) String() string { return proto.CompactTextString(m) }
func (*OTPValidateResponse) ProtoMessage()    {}
func (*OTPValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_otp_21fb56b2fc8393a0, []int{3}
}
func (m *OTPValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OTPValidateResponse.Unmarshal(m, b)
}
func (m *OTPValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OTPValidateResponse.Marshal(b, m, deterministic)
}
func (dst *OTPValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OTPValidateResponse.Merge(dst, src)
}
func (m *OTPValidateResponse) XXX_Size() int {
	return xxx_messageInfo_OTPValidateResponse.Size(m)
}
func (m *OTPValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OTPValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OTPValidateResponse proto.InternalMessageInfo

func (m *OTPValidateResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *OTPValidateResponse) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func init() {
	proto.RegisterType((*OTPEnrollment)(nil), "twoferrpc.OTPEnrollment")
	proto.RegisterType((*OTPEnrollmentResponse)(nil), "twoferrpc.OTPEnrollmentResponse")
	proto.RegisterType((*OTPValidate)(nil), "twoferrpc.OTPValidate")
	proto.RegisterType((*OTPValidateResponse)(nil), "twoferrpc.OTPValidateResponse")
	proto.RegisterEnum("twoferrpc.OTPAlg", OTPAlg_name, OTPAlg_value)
	proto.RegisterEnum("twoferrpc.OTPMode", OTPMode_name, OTPMode_value)
	proto.RegisterEnum("twoferrpc.OTPDigits", OTPDigits_name, OTPDigits_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for OTP service

type OTPClient interface {
	Enroll(ctx context.Context, in *OTPEnrollment, opts ...grpc.CallOption) (*OTPEnrollmentResponse, error)
	Validate(ctx context.Context, in *OTPValidate, opts ...grpc.CallOption) (*OTPValidateResponse, error)
}

type oTPClient struct {
	cc *grpc.ClientConn
}

func NewOTPClient(cc *grpc.ClientConn) OTPClient {
	return &oTPClient{cc}
}

func (c *oTPClient) Enroll(ctx context.Context, in *OTPEnrollment, opts ...grpc.CallOption) (*OTPEnrollmentResponse, error) {
	out := new(OTPEnrollmentResponse)
	err := grpc.Invoke(ctx, "/twoferrpc.OTP/Enroll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPClient) Validate(ctx context.Context, in *OTPValidate, opts ...grpc.CallOption) (*OTPValidateResponse, error) {
	out := new(OTPValidateResponse)
	err := grpc.Invoke(ctx, "/twoferrpc.OTP/Validate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OTP service

type OTPServer interface {
	Enroll(context.Context, *OTPEnrollment) (*OTPEnrollmentResponse, error)
	Validate(context.Context, *OTPValidate) (*OTPValidateResponse, error)
}

func RegisterOTPServer(s *grpc.Server, srv OTPServer) {
	s.RegisterService(&_OTP_serviceDesc, srv)
}

func _OTP_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTPEnrollment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twoferrpc.OTP/Enroll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPServer).Enroll(ctx, req.(*OTPEnrollment))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTP_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTPValidate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twoferrpc.OTP/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPServer).Validate(ctx, req.(*OTPValidate))
	}
	return interceptor(ctx, in, info, handler)
}

var _OTP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twoferrpc.OTP",
	HandlerType: (*OTPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _OTP_Enroll_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _OTP_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "otp.proto",
}

func init() { proto.RegisterFile("otp.proto", fileDescriptor_otp_21fb56b2fc8393a0) }

var fileDescriptor_otp_21fb56b2fc8393a0 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0xde, 0x69, 0xb6, 0xc9, 0xe6, 0x94, 0x4a, 0x3c, 0xd6, 0x32, 0xf4, 0xa2, 0x86, 0x08, 0xb2,
	0x2c, 0xba, 0xd0, 0x48, 0xf5, 0x7a, 0x69, 0xa3, 0xdd, 0x8b, 0x9a, 0x30, 0x1b, 0xc5, 0x3b, 0x89,
	0xc9, 0xb8, 0x04, 0xd2, 0x4c, 0x98, 0xcc, 0x2a, 0xf8, 0x1a, 0xbe, 0xaa, 0x0f, 0x20, 0x99, 0xfc,
	0x74, 0x03, 0xee, 0xdd, 0x7c, 0xe7, 0xfb, 0x99, 0x9c, 0x2f, 0x03, 0xb6, 0x50, 0xd5, 0xb2, 0x92,
	0x42, 0x09, 0xb4, 0xd5, 0x2f, 0xf1, 0x83, 0x4b, 0x59, 0xa5, 0xde, 0x5f, 0x02, 0xa7, 0x61, 0x1c,
	0x05, 0xa5, 0x14, 0x45, 0xf1, 0xc0, 0x4b, 0x85, 0xe7, 0x60, 0xe6, 0x75, 0xbd, 0xe3, 0x92, 0x12,
	0x97, 0xcc, 0x6d, 0xd6, 0x21, 0xa4, 0x60, 0x25, 0x69, 0x2a, 0x76, 0xa5, 0xa2, 0x47, 0x9a, 0xe8,
	0x21, 0xbe, 0x04, 0x23, 0x29, 0xb6, 0xd4, 0x70, 0xc9, 0xfc, 0x89, 0xff, 0x74, 0x39, 0x84, 0x2f,
	0xc3, 0x38, 0x5a, 0x15, 0x5b, 0xd6, 0xb0, 0xf8, 0x0a, 0xa6, 0x0f, 0x22, 0xe3, 0x74, 0xaa, 0x55,
	0x38, 0x56, 0xdd, 0x8b, 0x8c, 0x33, 0xcd, 0xe3, 0x6b, 0x30, 0xb3, 0x7c, 0x9b, 0xab, 0x9a, 0x9a,
	0x5a, 0x79, 0x36, 0x56, 0xde, 0x6a, 0x8e, 0x75, 0x9a, 0xe6, 0x63, 0x2b, 0x2e, 0x73, 0x91, 0x51,
	0xcb, 0x25, 0xf3, 0x53, 0xd6, 0x21, 0xbc, 0x04, 0xa8, 0x79, 0x2a, 0xb9, 0xda, 0xe4, 0xbf, 0x39,
	0x9d, 0x69, 0x6e, 0x6f, 0xe2, 0xad, 0xe0, 0xf9, 0x68, 0x6b, 0xc6, 0xeb, 0x4a, 0x94, 0x35, 0x47,
	0x07, 0x8c, 0x9d, 0xcc, 0xbb, 0xd5, 0x9b, 0x63, 0x73, 0x45, 0x6b, 0xec, 0xd6, 0xee, 0x90, 0xf7,
	0x1e, 0x4e, 0xc2, 0x38, 0xfa, 0x92, 0x14, 0x79, 0x96, 0x28, 0x6d, 0x14, 0xaa, 0xea, 0x8d, 0x42,
	0x55, 0x07, 0x8d, 0x37, 0xf0, 0x6c, 0xcf, 0x38, 0xdc, 0x7c, 0x06, 0xc7, 0x3f, 0x9b, 0x99, 0x8e,
	0x98, 0xb1, 0x16, 0x1c, 0x0a, 0x59, 0xbc, 0x01, 0xb3, 0x6d, 0x17, 0x6d, 0x38, 0xde, 0xdc, 0xad,
	0xbe, 0x5d, 0x39, 0x13, 0x3c, 0x01, 0xab, 0x39, 0xfa, 0xd7, 0xef, 0x1c, 0xd2, 0x83, 0xeb, 0x2b,
	0xdf, 0x39, 0x5a, 0xb8, 0x60, 0x75, 0x35, 0xe3, 0x0c, 0xa6, 0xf1, 0xfa, 0x3e, 0x68, 0xe5, 0x37,
	0xe1, 0xe7, 0x4f, 0x71, 0xc0, 0x1c, 0xb2, 0x78, 0x01, 0xf6, 0x50, 0x2f, 0x5a, 0x60, 0x6c, 0xd6,
	0x5f, 0x9d, 0x49, 0x13, 0x1e, 0xac, 0x3f, 0xde, 0xc5, 0x0e, 0xf1, 0xff, 0x10, 0x30, 0xc2, 0x38,
	0xc2, 0x0f, 0x60, 0xb6, 0xbd, 0x21, 0x1d, 0xff, 0x9a, 0xc7, 0x36, 0x2f, 0xdc, 0x43, 0x4c, 0xbf,
	0xad, 0x37, 0xc1, 0x5b, 0x98, 0x0d, 0xe5, 0x9d, 0x8f, 0xf5, 0xfd, 0xfc, 0xe2, 0xf2, 0xff, 0xf3,
	0xc7, 0x94, 0xef, 0xa6, 0x7e, 0xd1, 0x6f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xd4, 0x05,
	0xdd, 0xde, 0x02, 0x00, 0x00,
}
