// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qr.proto

package twoferrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QRData_Recovery int32

const (
	// Level L: 7% error recovery.
	QRData_LOW QRData_Recovery = 0
	// Level M: 15% error recovery. Good default choice.
	QRData_MEDIUM QRData_Recovery = 1
	// Level Q: 25% error recovery.
	QRData_HIGH QRData_Recovery = 2
	// Level H: 30% error recovery.
	QRData_HIGHEST QRData_Recovery = 3
)

var QRData_Recovery_name = map[int32]string{
	0: "LOW",
	1: "MEDIUM",
	2: "HIGH",
	3: "HIGHEST",
}
var QRData_Recovery_value = map[string]int32{
	"LOW":     0,
	"MEDIUM":  1,
	"HIGH":    2,
	"HIGHEST": 3,
}

func (x QRData_Recovery) String() string {
	return proto.EnumName(QRData_Recovery_name, int32(x))
}
func (QRData_Recovery) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_qr_3be733bb5ad99f07, []int{0, 0}
}

type QRData struct {
	RecoveryLevel        QRData_Recovery `protobuf:"varint,1,opt,name=RecoveryLevel,enum=twoferrpc.QRData_Recovery" json:"RecoveryLevel,omitempty"`
	Size                 int32           `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Data                 string          `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QRData) Reset()         { *m = QRData{} }
func (m *QRData) String() string { return proto.CompactTextString(m) }
func (*QRData) ProtoMessage()    {}
func (*QRData) Descriptor() ([]byte, []int) {
	return fileDescriptor_qr_3be733bb5ad99f07, []int{0}
}
func (m *QRData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QRData.Unmarshal(m, b)
}
func (m *QRData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QRData.Marshal(b, m, deterministic)
}
func (dst *QRData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QRData.Merge(dst, src)
}
func (m *QRData) XXX_Size() int {
	return xxx_messageInfo_QRData.Size(m)
}
func (m *QRData) XXX_DiscardUnknown() {
	xxx_messageInfo_QRData.DiscardUnknown(m)
}

var xxx_messageInfo_QRData proto.InternalMessageInfo

func (m *QRData) GetRecoveryLevel() QRData_Recovery {
	if m != nil {
		return m.RecoveryLevel
	}
	return QRData_LOW
}

func (m *QRData) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *QRData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type QRImage struct {
	ContentType          string   `protobuf:"bytes,1,opt,name=contentType" json:"contentType,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QRImage) Reset()         { *m = QRImage{} }
func (m *QRImage) String() string { return proto.CompactTextString(m) }
func (*QRImage) ProtoMessage()    {}
func (*QRImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_qr_3be733bb5ad99f07, []int{1}
}
func (m *QRImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QRImage.Unmarshal(m, b)
}
func (m *QRImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QRImage.Marshal(b, m, deterministic)
}
func (dst *QRImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QRImage.Merge(dst, src)
}
func (m *QRImage) XXX_Size() int {
	return xxx_messageInfo_QRImage.Size(m)
}
func (m *QRImage) XXX_DiscardUnknown() {
	xxx_messageInfo_QRImage.DiscardUnknown(m)
}

var xxx_messageInfo_QRImage proto.InternalMessageInfo

func (m *QRImage) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *QRImage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*QRData)(nil), "twoferrpc.QRData")
	proto.RegisterType((*QRImage)(nil), "twoferrpc.QRImage")
	proto.RegisterEnum("twoferrpc.QRData_Recovery", QRData_Recovery_name, QRData_Recovery_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for QR service

type QRClient interface {
	Generate(ctx context.Context, in *QRData, opts ...grpc.CallOption) (*QRImage, error)
}

type qRClient struct {
	cc *grpc.ClientConn
}

func NewQRClient(cc *grpc.ClientConn) QRClient {
	return &qRClient{cc}
}

func (c *qRClient) Generate(ctx context.Context, in *QRData, opts ...grpc.CallOption) (*QRImage, error) {
	out := new(QRImage)
	err := grpc.Invoke(ctx, "/twoferrpc.QR/Generate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for QR service

type QRServer interface {
	Generate(context.Context, *QRData) (*QRImage, error)
}

func RegisterQRServer(s *grpc.Server, srv QRServer) {
	s.RegisterService(&_QR_serviceDesc, srv)
}

func _QR_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twoferrpc.QR/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRServer).Generate(ctx, req.(*QRData))
	}
	return interceptor(ctx, in, info, handler)
}

var _QR_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twoferrpc.QR",
	HandlerType: (*QRServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _QR_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qr.proto",
}

func init() { proto.RegisterFile("qr.proto", fileDescriptor_qr_3be733bb5ad99f07) }

var fileDescriptor_qr_3be733bb5ad99f07 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xbb, 0x49, 0xcd, 0x9f, 0xa9, 0x4a, 0x9c, 0x53, 0xe8, 0x29, 0xe4, 0x94, 0xd3, 0x1e,
	0x5a, 0x10, 0x3c, 0xe9, 0xa1, 0xa5, 0x0d, 0xb4, 0x48, 0xc6, 0x8a, 0xe7, 0x35, 0x8e, 0x22, 0x68,
	0x36, 0xae, 0x4b, 0xa5, 0x7e, 0x24, 0x3f, 0xa5, 0x64, 0x4b, 0x8b, 0xc1, 0xdb, 0xe3, 0xf1, 0x1e,
	0xbf, 0x37, 0x03, 0xd1, 0x87, 0x91, 0xad, 0xd1, 0x56, 0x63, 0x6c, 0xbf, 0xf4, 0x33, 0x1b, 0xd3,
	0xd6, 0xf9, 0x8f, 0x80, 0xa0, 0xa2, 0x99, 0xb2, 0x0a, 0x6f, 0xe0, 0x8c, 0xb8, 0xd6, 0x5b, 0x36,
	0xbb, 0x15, 0x6f, 0xf9, 0x2d, 0x15, 0x99, 0x28, 0xce, 0x27, 0x63, 0x79, 0x4c, 0xcb, 0x7d, 0x52,
	0x1e, 0x62, 0xd4, 0x2f, 0x20, 0xc2, 0xf0, 0xf3, 0xf5, 0x9b, 0x53, 0x2f, 0x13, 0xc5, 0x09, 0x39,
	0xdd, 0x79, 0x4f, 0xca, 0xaa, 0xd4, 0xcf, 0x44, 0x11, 0x93, 0xd3, 0xf9, 0x25, 0x44, 0x87, 0x22,
	0x86, 0xe0, 0xaf, 0x6e, 0x1f, 0x92, 0x01, 0x02, 0x04, 0xeb, 0xf9, 0xac, 0xbc, 0x5f, 0x27, 0x02,
	0x23, 0x18, 0x2e, 0xcb, 0xc5, 0x32, 0xf1, 0x70, 0x04, 0x61, 0xa7, 0xe6, 0x77, 0x9b, 0xc4, 0xcf,
	0xaf, 0x21, 0xac, 0xa8, 0x7c, 0x57, 0x2f, 0x8c, 0x19, 0x8c, 0x6a, 0xdd, 0x58, 0x6e, 0xec, 0x66,
	0xd7, 0xb2, 0x9b, 0x1a, 0xd3, 0x5f, 0xeb, 0x08, 0xee, 0xc6, 0x9c, 0xee, 0xc1, 0x93, 0x2b, 0xf0,
	0x2a, 0xc2, 0x29, 0x44, 0x0b, 0x6e, 0xd8, 0x28, 0xcb, 0x78, 0xf1, 0xef, 0xba, 0x31, 0xf6, 0x2c,
	0x87, 0xcb, 0x07, 0x8f, 0x81, 0x7b, 0xdd, 0xf4, 0x37, 0x00, 0x00, 0xff, 0xff, 0x40, 0x9e, 0xc0,
	0xf7, 0x46, 0x01, 0x00, 0x00,
}
