// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pwd.proto

package gpwd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Alg int32

const (
	Alg_SHA_256 Alg = 0
	Alg_SHA_512 Alg = 1
	Alg_SCrypt  Alg = 2
	Alg_BCrypt  Alg = 3
)

var Alg_name = map[int32]string{
	0: "SHA_256",
	1: "SHA_512",
	2: "SCrypt",
	3: "BCrypt",
}
var Alg_value = map[string]int32{
	"SHA_256": 0,
	"SHA_512": 1,
	"SCrypt":  2,
	"BCrypt":  3,
}

func (x Alg) String() string {
	return proto.EnumName(Alg_name, int32(x))
}
func (Alg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pwd_5b7acb67e50dc5ce, []int{0}
}

type EnrollReq struct {
	Password             string   `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollReq) Reset()         { *m = EnrollReq{} }
func (m *EnrollReq) String() string { return proto.CompactTextString(m) }
func (*EnrollReq) ProtoMessage()    {}
func (*EnrollReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_pwd_5b7acb67e50dc5ce, []int{0}
}
func (m *EnrollReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollReq.Unmarshal(m, b)
}
func (m *EnrollReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollReq.Marshal(b, m, deterministic)
}
func (dst *EnrollReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollReq.Merge(dst, src)
}
func (m *EnrollReq) XXX_Size() int {
	return xxx_messageInfo_EnrollReq.Size(m)
}
func (m *EnrollReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollReq.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollReq proto.InternalMessageInfo

func (m *EnrollReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthReq struct {
	Password             string   `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	UserBlob             string   `protobuf:"bytes,2,opt,name=userBlob" json:"userBlob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_pwd_5b7acb67e50dc5ce, []int{1}
}
func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (dst *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(dst, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthReq) GetUserBlob() string {
	if m != nil {
		return m.UserBlob
	}
	return ""
}

type Res struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Res) Reset()         { *m = Res{} }
func (m *Res) String() string { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()    {}
func (*Res) Descriptor() ([]byte, []int) {
	return fileDescriptor_pwd_5b7acb67e50dc5ce, []int{2}
}
func (m *Res) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Res.Unmarshal(m, b)
}
func (m *Res) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Res.Marshal(b, m, deterministic)
}
func (dst *Res) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Res.Merge(dst, src)
}
func (m *Res) XXX_Size() int {
	return xxx_messageInfo_Res.Size(m)
}
func (m *Res) XXX_DiscardUnknown() {
	xxx_messageInfo_Res.DiscardUnknown(m)
}

var xxx_messageInfo_Res proto.InternalMessageInfo

func (m *Res) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Res) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Blob struct {
	UserBlob             string   `protobuf:"bytes,1,opt,name=userBlob" json:"userBlob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blob) Reset()         { *m = Blob{} }
func (m *Blob) String() string { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()    {}
func (*Blob) Descriptor() ([]byte, []int) {
	return fileDescriptor_pwd_5b7acb67e50dc5ce, []int{3}
}
func (m *Blob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blob.Unmarshal(m, b)
}
func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blob.Marshal(b, m, deterministic)
}
func (dst *Blob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob.Merge(dst, src)
}
func (m *Blob) XXX_Size() int {
	return xxx_messageInfo_Blob.Size(m)
}
func (m *Blob) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob.DiscardUnknown(m)
}

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetUserBlob() string {
	if m != nil {
		return m.UserBlob
	}
	return ""
}

func init() {
	proto.RegisterType((*EnrollReq)(nil), "gpwd.EnrollReq")
	proto.RegisterType((*AuthReq)(nil), "gpwd.AuthReq")
	proto.RegisterType((*Res)(nil), "gpwd.Res")
	proto.RegisterType((*Blob)(nil), "gpwd.Blob")
	proto.RegisterEnum("gpwd.Alg", Alg_name, Alg_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PWD service

type PWDClient interface {
	Enroll(ctx context.Context, in *EnrollReq, opts ...grpc.CallOption) (*Blob, error)
	Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*Res, error)
	Upgrade(ctx context.Context, in *Blob, opts ...grpc.CallOption) (*Blob, error)
}

type pWDClient struct {
	cc *grpc.ClientConn
}

func NewPWDClient(cc *grpc.ClientConn) PWDClient {
	return &pWDClient{cc}
}

func (c *pWDClient) Enroll(ctx context.Context, in *EnrollReq, opts ...grpc.CallOption) (*Blob, error) {
	out := new(Blob)
	err := grpc.Invoke(ctx, "/gpwd.PWD/Enroll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pWDClient) Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := grpc.Invoke(ctx, "/gpwd.PWD/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pWDClient) Upgrade(ctx context.Context, in *Blob, opts ...grpc.CallOption) (*Blob, error) {
	out := new(Blob)
	err := grpc.Invoke(ctx, "/gpwd.PWD/Upgrade", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PWD service

type PWDServer interface {
	Enroll(context.Context, *EnrollReq) (*Blob, error)
	Auth(context.Context, *AuthReq) (*Res, error)
	Upgrade(context.Context, *Blob) (*Blob, error)
}

func RegisterPWDServer(s *grpc.Server, srv PWDServer) {
	s.RegisterService(&_PWD_serviceDesc, srv)
}

func _PWD_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PWDServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpwd.PWD/Enroll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PWDServer).Enroll(ctx, req.(*EnrollReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PWD_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PWDServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpwd.PWD/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PWDServer).Auth(ctx, req.(*AuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PWD_Upgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Blob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PWDServer).Upgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpwd.PWD/Upgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PWDServer).Upgrade(ctx, req.(*Blob))
	}
	return interceptor(ctx, in, info, handler)
}

var _PWD_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gpwd.PWD",
	HandlerType: (*PWDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _PWD_Enroll_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _PWD_Auth_Handler,
		},
		{
			MethodName: "Upgrade",
			Handler:    _PWD_Upgrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pwd.proto",
}

func init() { proto.RegisterFile("pwd.proto", fileDescriptor_pwd_5b7acb67e50dc5ce) }

var fileDescriptor_pwd_5b7acb67e50dc5ce = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4b, 0x84, 0x40,
	0x14, 0xc6, 0x75, 0x35, 0x5d, 0x5f, 0x44, 0xf2, 0xe8, 0x20, 0x9e, 0x62, 0x3a, 0x6c, 0x74, 0x10,
	0x32, 0xac, 0xb3, 0x5b, 0x41, 0xc7, 0x98, 0x25, 0x3a, 0x86, 0x8b, 0x83, 0x05, 0x53, 0x33, 0xcd,
	0xb8, 0x49, 0xff, 0x7d, 0xcc, 0xbe, 0x75, 0xc9, 0xd3, 0xde, 0xde, 0xef, 0x3d, 0xbf, 0x0f, 0xfc,
	0x0d, 0x24, 0x7a, 0x68, 0x0b, 0x6d, 0x54, 0xaf, 0x30, 0xec, 0xf4, 0xd0, 0xb2, 0x05, 0x24, 0x8f,
	0x5f, 0x46, 0x49, 0xc9, 0xc5, 0x37, 0xe6, 0x30, 0xd7, 0x8d, 0xb5, 0x83, 0x32, 0x6d, 0xe6, 0x9f,
	0xfb, 0x97, 0x09, 0xdf, 0x33, 0xab, 0x21, 0xae, 0x37, 0xfd, 0xfb, 0x81, 0xcf, 0xdc, 0x6d, 0x63,
	0x85, 0x59, 0x4a, 0xb5, 0xce, 0x66, 0x74, 0x1b, 0x99, 0x55, 0x10, 0x70, 0x61, 0xf1, 0x0c, 0x8e,
	0x7e, 0x1a, 0xf9, 0x41, 0xd9, 0x39, 0x27, 0xc0, 0x0c, 0xe2, 0x4f, 0x61, 0x6d, 0xd3, 0x89, 0x5d,
	0x6e, 0x44, 0xc6, 0x20, 0x74, 0xf1, 0x49, 0xb5, 0x3f, 0xad, 0xbe, 0xba, 0x83, 0xa0, 0x96, 0x1d,
	0x1e, 0x43, 0xbc, 0x7a, 0xaa, 0xdf, 0xca, 0xea, 0x36, 0xf5, 0x46, 0xa8, 0xae, 0xcb, 0xd4, 0x47,
	0x80, 0x68, 0x75, 0x6f, 0x7e, 0x75, 0x9f, 0xce, 0xdc, 0xbc, 0xa4, 0x39, 0x28, 0x07, 0x08, 0x9e,
	0x5f, 0x1f, 0x70, 0x01, 0x11, 0x69, 0xc0, 0xd3, 0xc2, 0x79, 0x29, 0xf6, 0x52, 0x72, 0xa0, 0xc5,
	0xf6, 0x0f, 0x3c, 0x64, 0x10, 0x3a, 0x0d, 0x78, 0x42, 0xdb, 0x9d, 0x92, 0x3c, 0x21, 0xe4, 0xc2,
	0x32, 0x0f, 0x2f, 0x20, 0x7e, 0xd1, 0x9d, 0x69, 0x5a, 0x81, 0xff, 0xc2, 0xd3, 0xa2, 0x75, 0xb4,
	0x7d, 0x85, 0x9b, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0xb5, 0x4e, 0x51, 0x92, 0x01, 0x00,
	0x00,
}
