FROM golang:1.14

RUN go get -u -v github.com/codeskyblue/fswatch

RUN mkdir -p /go/src/github.com/modfin/twofer
WORKDIR /go/src/github.com/modfin/twofer



RUN echo "cd /go/src/github.com/modfin/twofer/example/eid && go run ./*.go" > /run.sh

RUN printf "desc: \n\
triggers: \n\
- name: '' \n\
  pattens: \n\
  - '**/*.go' \n\
  env: \n\
    DEBUG: '1' \n\
  cmd: bash /run.sh \n\
  shell: true \n\
  delay: 100ms \n\
  stop_timeout: 500ms \n\
  signal: KILL \n\
  kill_signal: 'SIGTERM' \n\
watch_paths: \n\
- /go/src/github.com/modfin/twofer/example/eid \n\
watch_depth: 10 \n\
" >> /fsw.yml

CMD fswatch -config /fsw.yml

