// Code generated by protoc-gen-go. DO NOT EDIT.
// source: w6n.proto

package gw6n

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_w6n_e3bc94e1900f3629, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BeginRegisterRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	UserBlob             []byte   `protobuf:"bytes,2,opt,name=userBlob,proto3" json:"userBlob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginRegisterRequest) Reset()         { *m = BeginRegisterRequest{} }
func (m *BeginRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*BeginRegisterRequest) ProtoMessage()    {}
func (*BeginRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_w6n_e3bc94e1900f3629, []int{1}
}
func (m *BeginRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginRegisterRequest.Unmarshal(m, b)
}
func (m *BeginRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginRegisterRequest.Marshal(b, m, deterministic)
}
func (dst *BeginRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginRegisterRequest.Merge(dst, src)
}
func (m *BeginRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_BeginRegisterRequest.Size(m)
}
func (m *BeginRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeginRegisterRequest proto.InternalMessageInfo

func (m *BeginRegisterRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *BeginRegisterRequest) GetUserBlob() []byte {
	if m != nil {
		return m.UserBlob
	}
	return nil
}

type BeginRegisterResponse struct {
	Session              []byte   `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Json                 []byte   `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginRegisterResponse) Reset()         { *m = BeginRegisterResponse{} }
func (m *BeginRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*BeginRegisterResponse) ProtoMessage()    {}
func (*BeginRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_w6n_e3bc94e1900f3629, []int{2}
}
func (m *BeginRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginRegisterResponse.Unmarshal(m, b)
}
func (m *BeginRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginRegisterResponse.Marshal(b, m, deterministic)
}
func (dst *BeginRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginRegisterResponse.Merge(dst, src)
}
func (m *BeginRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_BeginRegisterResponse.Size(m)
}
func (m *BeginRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BeginRegisterResponse proto.InternalMessageInfo

func (m *BeginRegisterResponse) GetSession() []byte {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *BeginRegisterResponse) GetJson() []byte {
	if m != nil {
		return m.Json
	}
	return nil
}

type FinishRegisterRequest struct {
	UserBlob             []byte   `protobuf:"bytes,1,opt,name=userBlob,proto3" json:"userBlob,omitempty"`
	Session              []byte   `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinishRegisterRequest) Reset()         { *m = FinishRegisterRequest{} }
func (m *FinishRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*FinishRegisterRequest) ProtoMessage()    {}
func (*FinishRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_w6n_e3bc94e1900f3629, []int{3}
}
func (m *FinishRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishRegisterRequest.Unmarshal(m, b)
}
func (m *FinishRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishRegisterRequest.Marshal(b, m, deterministic)
}
func (dst *FinishRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishRegisterRequest.Merge(dst, src)
}
func (m *FinishRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_FinishRegisterRequest.Size(m)
}
func (m *FinishRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinishRegisterRequest proto.InternalMessageInfo

func (m *FinishRegisterRequest) GetUserBlob() []byte {
	if m != nil {
		return m.UserBlob
	}
	return nil
}

func (m *FinishRegisterRequest) GetSession() []byte {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *FinishRegisterRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type FinishRegisterResponse struct {
	UserBlob             []byte   `protobuf:"bytes,1,opt,name=userBlob,proto3" json:"userBlob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinishRegisterResponse) Reset()         { *m = FinishRegisterResponse{} }
func (m *FinishRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*FinishRegisterResponse) ProtoMessage()    {}
func (*FinishRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_w6n_e3bc94e1900f3629, []int{4}
}
func (m *FinishRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishRegisterResponse.Unmarshal(m, b)
}
func (m *FinishRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishRegisterResponse.Marshal(b, m, deterministic)
}
func (dst *FinishRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishRegisterResponse.Merge(dst, src)
}
func (m *FinishRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_FinishRegisterResponse.Size(m)
}
func (m *FinishRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FinishRegisterResponse proto.InternalMessageInfo

func (m *FinishRegisterResponse) GetUserBlob() []byte {
	if m != nil {
		return m.UserBlob
	}
	return nil
}

type BeginLoginRequest struct {
	UserBlob             []byte   `protobuf:"bytes,1,opt,name=userBlob,proto3" json:"userBlob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginLoginRequest) Reset()         { *m = BeginLoginRequest{} }
func (m *BeginLoginRequest) String() string { return proto.CompactTextString(m) }
func (*BeginLoginRequest) ProtoMessage()    {}
func (*BeginLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_w6n_e3bc94e1900f3629, []int{5}
}
func (m *BeginLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginLoginRequest.Unmarshal(m, b)
}
func (m *BeginLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginLoginRequest.Marshal(b, m, deterministic)
}
func (dst *BeginLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginLoginRequest.Merge(dst, src)
}
func (m *BeginLoginRequest) XXX_Size() int {
	return xxx_messageInfo_BeginLoginRequest.Size(m)
}
func (m *BeginLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeginLoginRequest proto.InternalMessageInfo

func (m *BeginLoginRequest) GetUserBlob() []byte {
	if m != nil {
		return m.UserBlob
	}
	return nil
}

type BeginLoginResponse struct {
	Session              []byte   `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Json                 []byte   `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginLoginResponse) Reset()         { *m = BeginLoginResponse{} }
func (m *BeginLoginResponse) String() string { return proto.CompactTextString(m) }
func (*BeginLoginResponse) ProtoMessage()    {}
func (*BeginLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_w6n_e3bc94e1900f3629, []int{6}
}
func (m *BeginLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginLoginResponse.Unmarshal(m, b)
}
func (m *BeginLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginLoginResponse.Marshal(b, m, deterministic)
}
func (dst *BeginLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginLoginResponse.Merge(dst, src)
}
func (m *BeginLoginResponse) XXX_Size() int {
	return xxx_messageInfo_BeginLoginResponse.Size(m)
}
func (m *BeginLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BeginLoginResponse proto.InternalMessageInfo

func (m *BeginLoginResponse) GetSession() []byte {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *BeginLoginResponse) GetJson() []byte {
	if m != nil {
		return m.Json
	}
	return nil
}

type FinishLoginRequest struct {
	UserBlob             []byte   `protobuf:"bytes,1,opt,name=userBlob,proto3" json:"userBlob,omitempty"`
	Session              []byte   `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinishLoginRequest) Reset()         { *m = FinishLoginRequest{} }
func (m *FinishLoginRequest) String() string { return proto.CompactTextString(m) }
func (*FinishLoginRequest) ProtoMessage()    {}
func (*FinishLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_w6n_e3bc94e1900f3629, []int{7}
}
func (m *FinishLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishLoginRequest.Unmarshal(m, b)
}
func (m *FinishLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishLoginRequest.Marshal(b, m, deterministic)
}
func (dst *FinishLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishLoginRequest.Merge(dst, src)
}
func (m *FinishLoginRequest) XXX_Size() int {
	return xxx_messageInfo_FinishLoginRequest.Size(m)
}
func (m *FinishLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinishLoginRequest proto.InternalMessageInfo

func (m *FinishLoginRequest) GetUserBlob() []byte {
	if m != nil {
		return m.UserBlob
	}
	return nil
}

func (m *FinishLoginRequest) GetSession() []byte {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *FinishLoginRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type FinishLoginResponse struct {
	UserBlob             []byte   `protobuf:"bytes,1,opt,name=userBlob,proto3" json:"userBlob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinishLoginResponse) Reset()         { *m = FinishLoginResponse{} }
func (m *FinishLoginResponse) String() string { return proto.CompactTextString(m) }
func (*FinishLoginResponse) ProtoMessage()    {}
func (*FinishLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_w6n_e3bc94e1900f3629, []int{8}
}
func (m *FinishLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishLoginResponse.Unmarshal(m, b)
}
func (m *FinishLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishLoginResponse.Marshal(b, m, deterministic)
}
func (dst *FinishLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishLoginResponse.Merge(dst, src)
}
func (m *FinishLoginResponse) XXX_Size() int {
	return xxx_messageInfo_FinishLoginResponse.Size(m)
}
func (m *FinishLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FinishLoginResponse proto.InternalMessageInfo

func (m *FinishLoginResponse) GetUserBlob() []byte {
	if m != nil {
		return m.UserBlob
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "gw6n.User")
	proto.RegisterType((*BeginRegisterRequest)(nil), "gw6n.BeginRegisterRequest")
	proto.RegisterType((*BeginRegisterResponse)(nil), "gw6n.BeginRegisterResponse")
	proto.RegisterType((*FinishRegisterRequest)(nil), "gw6n.FinishRegisterRequest")
	proto.RegisterType((*FinishRegisterResponse)(nil), "gw6n.FinishRegisterResponse")
	proto.RegisterType((*BeginLoginRequest)(nil), "gw6n.BeginLoginRequest")
	proto.RegisterType((*BeginLoginResponse)(nil), "gw6n.BeginLoginResponse")
	proto.RegisterType((*FinishLoginRequest)(nil), "gw6n.FinishLoginRequest")
	proto.RegisterType((*FinishLoginResponse)(nil), "gw6n.FinishLoginResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WebAuthn service

type WebAuthnClient interface {
	BeginRegister(ctx context.Context, in *BeginRegisterRequest, opts ...grpc.CallOption) (*BeginRegisterResponse, error)
	FinishRegister(ctx context.Context, in *FinishRegisterRequest, opts ...grpc.CallOption) (*FinishRegisterResponse, error)
	BeginLogin(ctx context.Context, in *BeginLoginRequest, opts ...grpc.CallOption) (*BeginLoginResponse, error)
	FinishLogin(ctx context.Context, in *FinishLoginRequest, opts ...grpc.CallOption) (*FinishLoginResponse, error)
}

type webAuthnClient struct {
	cc *grpc.ClientConn
}

func NewWebAuthnClient(cc *grpc.ClientConn) WebAuthnClient {
	return &webAuthnClient{cc}
}

func (c *webAuthnClient) BeginRegister(ctx context.Context, in *BeginRegisterRequest, opts ...grpc.CallOption) (*BeginRegisterResponse, error) {
	out := new(BeginRegisterResponse)
	err := grpc.Invoke(ctx, "/gw6n.WebAuthn/BeginRegister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnClient) FinishRegister(ctx context.Context, in *FinishRegisterRequest, opts ...grpc.CallOption) (*FinishRegisterResponse, error) {
	out := new(FinishRegisterResponse)
	err := grpc.Invoke(ctx, "/gw6n.WebAuthn/FinishRegister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnClient) BeginLogin(ctx context.Context, in *BeginLoginRequest, opts ...grpc.CallOption) (*BeginLoginResponse, error) {
	out := new(BeginLoginResponse)
	err := grpc.Invoke(ctx, "/gw6n.WebAuthn/BeginLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webAuthnClient) FinishLogin(ctx context.Context, in *FinishLoginRequest, opts ...grpc.CallOption) (*FinishLoginResponse, error) {
	out := new(FinishLoginResponse)
	err := grpc.Invoke(ctx, "/gw6n.WebAuthn/FinishLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WebAuthn service

type WebAuthnServer interface {
	BeginRegister(context.Context, *BeginRegisterRequest) (*BeginRegisterResponse, error)
	FinishRegister(context.Context, *FinishRegisterRequest) (*FinishRegisterResponse, error)
	BeginLogin(context.Context, *BeginLoginRequest) (*BeginLoginResponse, error)
	FinishLogin(context.Context, *FinishLoginRequest) (*FinishLoginResponse, error)
}

func RegisterWebAuthnServer(s *grpc.Server, srv WebAuthnServer) {
	s.RegisterService(&_WebAuthn_serviceDesc, srv)
}

func _WebAuthn_BeginRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServer).BeginRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gw6n.WebAuthn/BeginRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServer).BeginRegister(ctx, req.(*BeginRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthn_FinishRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServer).FinishRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gw6n.WebAuthn/FinishRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServer).FinishRegister(ctx, req.(*FinishRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthn_BeginLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServer).BeginLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gw6n.WebAuthn/BeginLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServer).BeginLogin(ctx, req.(*BeginLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebAuthn_FinishLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebAuthnServer).FinishLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gw6n.WebAuthn/FinishLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebAuthnServer).FinishLogin(ctx, req.(*FinishLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WebAuthn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gw6n.WebAuthn",
	HandlerType: (*WebAuthnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginRegister",
			Handler:    _WebAuthn_BeginRegister_Handler,
		},
		{
			MethodName: "FinishRegister",
			Handler:    _WebAuthn_FinishRegister_Handler,
		},
		{
			MethodName: "BeginLogin",
			Handler:    _WebAuthn_BeginLogin_Handler,
		},
		{
			MethodName: "FinishLogin",
			Handler:    _WebAuthn_FinishLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "w6n.proto",
}

func init() { proto.RegisterFile("w6n.proto", fileDescriptor_w6n_e3bc94e1900f3629) }

var fileDescriptor_w6n_e3bc94e1900f3629 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0x80, 0xa5, 0x36, 0x0a, 0x03, 0x92, 0x38, 0x8a, 0xd6, 0x4a, 0x8c, 0xd9, 0x93, 0xf1, 0x80,
	0x11, 0x0d, 0x77, 0x88, 0x7a, 0x30, 0x7a, 0xd9, 0xc4, 0x78, 0x86, 0x30, 0x29, 0xeb, 0xcf, 0x2e,
	0x76, 0xda, 0xf0, 0x56, 0x3e, 0xa3, 0xe9, 0xf2, 0xb7, 0xc5, 0x46, 0x0c, 0xa7, 0xee, 0xee, 0x64,
	0xbe, 0x6f, 0x76, 0x76, 0x0a, 0x95, 0x49, 0x47, 0xb7, 0xc6, 0xb1, 0x49, 0x0c, 0xfa, 0xd1, 0xa4,
	0xa3, 0xc5, 0x25, 0xf8, 0x2f, 0x4c, 0x31, 0xd6, 0xc1, 0x53, 0xc3, 0xa0, 0x74, 0x5e, 0xba, 0xa8,
	0x48, 0x4f, 0x0d, 0x11, 0xc1, 0xd7, 0xfd, 0x4f, 0x0a, 0x3c, 0x7b, 0x62, 0xd7, 0x42, 0xc2, 0x61,
	0x8f, 0x22, 0xa5, 0x25, 0x45, 0x8a, 0x13, 0x8a, 0x25, 0x7d, 0xa5, 0xc4, 0x09, 0x9e, 0x81, 0x9f,
	0x32, 0xc5, 0x36, 0xbb, 0xda, 0x86, 0x56, 0x06, 0x6e, 0x65, 0x54, 0x69, 0xcf, 0x31, 0x84, 0x72,
	0xf6, 0xed, 0x7d, 0x98, 0x81, 0xe5, 0xd5, 0xe4, 0x62, 0x2f, 0xee, 0xa1, 0xb1, 0xc2, 0xe4, 0xb1,
	0xd1, 0x4c, 0x18, 0xc0, 0x2e, 0x13, 0xb3, 0x32, 0xda, 0x72, 0x6b, 0x72, 0xbe, 0xcd, 0x4a, 0x7b,
	0x63, 0xa3, 0x67, 0x28, 0xbb, 0x16, 0xef, 0xd0, 0x78, 0x50, 0x5a, 0xf1, 0x68, 0xb5, 0x36, 0xd7,
	0x5d, 0xca, 0xbb, 0x5d, 0x85, 0x97, 0x57, 0x34, 0xa1, 0xc2, 0x2a, 0xd2, 0xfd, 0x24, 0x8d, 0x29,
	0xd8, 0xb6, 0xb1, 0xe5, 0x81, 0xb8, 0x85, 0xa3, 0x55, 0xd9, 0xac, 0xe8, 0x3f, 0x6c, 0xe2, 0x0a,
	0xf6, 0xed, 0x4d, 0x9f, 0x8c, 0xbd, 0xee, 0xda, 0xf2, 0x44, 0x0f, 0xd0, 0x4d, 0xd8, 0xa8, 0x2f,
	0x23, 0xc0, 0x69, 0xa9, 0xff, 0xb5, 0x6e, 0xdc, 0x94, 0x6b, 0x38, 0xc8, 0x99, 0xd6, 0x77, 0xa4,
	0xfd, 0xed, 0x41, 0xf9, 0x95, 0x06, 0xdd, 0x34, 0x19, 0x69, 0x7c, 0x84, 0xbd, 0xdc, 0x20, 0x60,
	0x38, 0x9d, 0xa3, 0xa2, 0x89, 0x0b, 0x4f, 0x0b, 0x63, 0x53, 0xa5, 0xd8, 0xc2, 0x67, 0xa8, 0xe7,
	0x1f, 0x08, 0x67, 0x09, 0x85, 0x33, 0x12, 0x36, 0x8b, 0x83, 0x0b, 0x5c, 0x17, 0x60, 0xf9, 0x10,
	0x78, 0xec, 0xb8, 0xdd, 0xae, 0x86, 0xc1, 0xef, 0xc0, 0x02, 0x71, 0x07, 0x55, 0xa7, 0x3b, 0x18,
	0xb8, 0xc6, 0x1c, 0xe4, 0xa4, 0x20, 0x32, 0xa7, 0x0c, 0x76, 0xec, 0x9f, 0x7b, 0xf3, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x22, 0xb9, 0x24, 0x8a, 0xc6, 0x03, 0x00, 0x00,
}
