FROM golang:1.24.6

RUN apt-get update && apt-get install -y inotify-hookable

RUN mkdir -p /go/src/github.com/modfin/twofer
WORKDIR /go/src/github.com/modfin/twofer

# run fswatch
CMD ./fw.sh serve start ./cmd/twoferd
