FROM golang:1.24.6-alpine3.22 AS builder

#RUN apk add --no-cache git curl build-base bash shadow

RUN mkdir -p /go/src/twofer
WORKDIR /go/src/twofer

COPY . /go/src/twofer

RUN ls

RUN CGO_ENABLE=0 go build -o /twoferd ./cmd/twoferd/main.go

FROM scratch
EXPOSE 8080
COPY --from=builder /twoferd /
CMD [ "/twoferd" ]
